name: go-leetcode

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    # 作业名称为 Build
    name: Go-Leetcode-CI/CD
    # 此作业在 Linux 上运行
    runs-on: ubuntu-18.04
    steps:
      # 设置go语言环境
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
      #检查是否存放在指定的目录里面
      - name: Check out code into the Go module directory
        uses:
          actions/checkout@v2
      #获取go的依赖
      - name: Get go dependencies
        run: |
          go mod tidy
      #运行指定的检查
      - name: Check code
        run: |
          go mod tidy
      #指定指定的构建脚本
      - name: Build
        run: bash unit-test/build.sh
      #运行指定的测试脚本
      - name: Test
        run: bash unit-test/run.sh
